# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Python Class
email: kennethsgoodman@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  This website was created to help users navigate through the class I put together. 
  You are more than welcome to use all the material here for free for whatever purpose you desire. 
  I will gladly take any feedback you may have.
baseurl: "pythonClass/" # the subpath of your site, e.g. /blog
url: "http://kennethgoodman.github.io/" # the base hostname & protocol for your site
github_username:  kennethgoodman
# Build settings
markdown: kramdown
